In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv')  # impproting survey_results_public csv file and creating a dataframe
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [3]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [4]:
df.columns.to_list() # list of all columns in dataframe

['Respondent',
 'MainBranch',
 'Hobbyist',
 'OpenSourcer',
 'OpenSource',
 'Employment',
 'Country',
 'Student',
 'EdLevel',
 'UndergradMajor',
 'EduOther',
 'OrgSize',
 'DevType',
 'YearsCode',
 'Age1stCode',
 'YearsCodePro',
 'CareerSat',
 'JobSat',
 'MgrIdiot',
 'MgrMoney',
 'MgrWant',
 'JobSeek',
 'LastHireDate',
 'LastInt',
 'FizzBuzz',
 'JobFactors',
 'ResumeUpdate',
 'CurrencySymbol',
 'CurrencyDesc',
 'CompTotal',
 'CompFreq',
 'Salary',
 'WorkWeekHrs',
 'WorkPlan',
 'WorkChallenge',
 'WorkRemote',
 'WorkLoc',
 'ImpSyn',
 'CodeRev',
 'CodeRevHrs',
 'UnitTests',
 'PurchaseHow',
 'PurchaseWhat',
 'LanguageWorkedWith',
 'LanguageDesireNextYear',
 'DatabaseWorkedWith',
 'DatabaseDesireNextYear',
 'PlatformWorkedWith',
 'PlatformDesireNextYear',
 'WebFrameWorkedWith',
 'WebFrameDesireNextYear',
 'MiscTechWorkedWith',
 'MiscTechDesireNextYear',
 'DevEnviron',
 'OpSys',
 'Containers',
 'BlockchainOrg',
 'BlockchainIs',
 'BetterLife',
 'ITperson',
 'OffOn',
 'SocialMedia',
 'Extraversion',
 'ScreenName',
 'SOVisit1st',
 'SOVisitFreq',
 'SOVisitTo',
 'SOFindAnswer',
 'SOTimeSaved',
 'SOHowMuchTime',
 'SOAccount',
 'SOPartFreq',
 'SOJobs',
 'EntTeams',
 'SOComm',
 'WelcomeChange',
 'SONewContent',
 'Age',
 'Gender',
 'Trans',
 'Sexuality',
 'Ethnicity',
 'Dependents',
 'SurveyLength',
 'SurveyEase']

In [5]:
# creating a filter that has all rows as true that has 'Hobbyist' column as 'Yes' otherwise as False.
fltr = (df['Hobbyist'] == 'Yes')

In [6]:
# using the filter to output only rows that has rows as True or that satify the condition
df[fltr].head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult

In [7]:
# we can also use loc to fetch the results using fltr
df.loc[fltr].head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult

In [8]:
# the benifit of using loc or iloc is that we can also select the columns that we want to ouput. 
# like in below example, we are outputting 3 columns, 'Respondent', 'Hobbyist' and 'ConvertedComp'
df.loc[fltr, ['Respondent', 'Hobbyist', 'Salary']].head()

   Respondent Hobbyist    Salary
0           1      Yes       NaN
2           3      Yes    8820.0
4           5      Yes       NaN
5           6      Yes  366420.0
7           8      Yes       NaN

In [9]:
# We can also use AND (&) and OR (|) operator to filter for more then one condition. 
# Filter that sets rows to True if respondent has Yes as hobbyist and salary of over 100,000 usd
fltr = ((df['Hobbyist'] == 'Yes') & (df['Salary'] > 100000))

In [10]:
# using the filter in our dataframe with loc
df.loc[fltr, ['Respondent', 'Hobbyist', 'Salary']]

     Respondent Hobbyist     Salary
5             6      Yes   366420.0
15           16      Yes   455352.0
21           22      Yes   103000.0
25           26      Yes   114000.0
38           39      Yes   156000.0
44           45      Yes   175000.0
46           47      Yes   187000.0
57           58      Yes  2000000.0
59           60      Yes   107000.0
65           66      Yes   137490.0
71           72      Yes   110352.0
73           74      Yes   114575.0
81           82      Yes   143932.0
82           83      Yes   117540.0
99          100      Yes   229016.0
105         106      Yes   160000.0
107         108      Yes   140000.0
115         116      Yes   103117.0
124         125      Yes   194800.0
126         127      Yes   106000.0
127         128      Yes  1000000.0
130         131      Yes   199450.0
146         148      Yes   135000.0
150         152      Yes   103117.0
153         155      Yes   962424.0
155         157      Yes   960000.0
158         160      Yes   150000.0
164         166      Yes  2000000.0

In [11]:
# we can also get the count of rows that satisfy the condition
df.loc[fltr, 'Respondent'].count()

28

In [12]:
# Using NOT operator 
# we can use ~ (tilda) sign to get the opposite of the filter.
df.loc[~fltr, 'Respondent'].count()

172

In [13]:
# Finding rows where Respondents have not shared salary
fltr = (df['Salary'].isnull())
df.loc[fltr, ['Respondent', 'Hobbyist', 'Salary']].head()

   Respondent Hobbyist  Salary
0           1      Yes     NaN
1           2       No     NaN
4           5      Yes     NaN
6           7       No     NaN
7           8      Yes     NaN

In [14]:
# df['CloumnName'].isnull() : returns rows as True who has a column as NaN.
fltr = df['Hobbyist'].isnull()
df.loc[fltr, 'Respondent'].count() # we have 0 number of Respondent with NaN as their answer for the Hobbyist question

0

In [15]:
# we have 60 number of Respondent with NaN as their answer for the Salary question
fltr = df['Salary'].isnull()
df.loc[fltr, 'Respondent'].count()

60

In [16]:
# df['CloumnName'].notnull() : This is opposite of isnull() It returns rows as true 
# if the value of the column is not NaN
fltr = df['Salary'].notnull()

In [17]:
# we have 140 number of Respondent with valid answer for the Salary question as n
df.loc[fltr, 'Respondent'].count()

140

In [39]:
# Excercise: Finding to 5 most common languages that people have worked with.

from collections import Counter  # import Counter

fltr = df['LanguageWorkedWith'].notnull()  # filter to remove NaN from our datasframe.
language = df.loc[fltr, 'LanguageWorkedWith'].to_list()  # applying filter and getting data in the form of list 
c_lang_known = Counter()  # creating a counter that counts the languages

for item in language:  # looping through all the items in language list
    lang_list = item.split(';')  # spliting each item in a list after spliting with ; to create another list
    c_lang_known.update(lang_list)  # using counter update method to count each element in the list

print(c_lang_known)  # printing the outcome
c_lang_known.most_common(5)  # printing the top 5 most common language

Counter({'JavaScript': 135, 'HTML/CSS': 130, 'SQL': 116, 'Python': 96, 'Java': 84, 'Bash/Shell/PowerShell': 76, 'C#': 56, 'C++': 54, 'TypeScript': 47, 'PHP': 46, 'C': 37, 'Ruby': 20, 'R': 17, 'Go': 16, 'Kotlin': 16, 'VBA': 15, 'Assembly': 14, 'Other(s):': 10, 'Objective-C': 10, 'Swift': 9, 'Scala': 7, 'Rust': 6, 'Clojure': 5, 'WebAssembly': 2, 'Elixir': 2, 'Erlang': 2, 'Dart': 2, 'F#': 1})

[('JavaScript', 135),
 ('HTML/CSS', 130),
 ('SQL', 116),
 ('Python', 96),
 ('Java', 84)]

In [42]:
# Excercise: Finding to 5 most common languages that people desire to learn.

from collections import Counter

fltr = df['LanguageDesireNextYear'].notnull()
desired_lang = df.loc[fltr, 'LanguageDesireNextYear'].to_list()
c_desired_lang = Counter()

for lang in desired_lang:
    c.update(lang.split(';'))

c.most_common(10)

[('JavaScript', 331),
 ('HTML/CSS', 316),
 ('SQL', 292),
 ('Python', 276),
 ('Bash/Shell/PowerShell', 186),
 ('Java', 184),
 ('C#', 160),
 ('TypeScript', 155),
 ('C++', 134),
 ('C', 93)]

In [48]:
# isin(list) filter
country_list = ['India', 'United Kingdom', 'United States', 'Australia', 'France', 'Netherlands']
fltr = df['Country'].isin(country_list)
df.loc[fltr, 'Country'].count()

91